name: Rotate wallpapers monthly

on:
  schedule:
    - cron: "0 0 1 * *" # 1er du mois
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run rotation script
        run: node scripts/rotate.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add active.json

          git commit -m "Monthly wallpaper rotation" || echo "No changes"
          git push
